### ISSUE TITLE
a bug for refresh page

### ISSUE THREAD

**Issue by CaryGuo** [MikaelEdebro/vue-airbnb-style-datepicker#10]
If the uri looks like http://www.abc.com/index.html/#/module/action/...... ,
then we chick on any grid of date, the page while be refresh. and the uri will be change to
http://www.abc.com/index.html/?#/module/action/...... 
Bug if "?" is exist, the bug will not be appear.
I can't find the reason for the bug, so i submit this issues.

**Comment by MikaelEdebro** [comment]
This doesn't seem to be related to the datepicker plugin. Why would you have ? before your route?

**Comment by CaryGuo** [comment]
Think you very much. I have resolved this bug. The date-picker is in a form meta, this form meta has a button trigger, if click a button, form will be request a new page. So, i use `@click.native.prevent` to prevent this trigger bubble.

**Comment by SxDx** [comment]
I think I have the same or a similar problem.
When you use the datepicker inside a form and almost every element inside the datepicker is a button the form gets submitted when clicking on elements. The default button type is `submit`(see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type).

Changing the button type to `button` fixes the problem, I can submit a pull request if there is no other/better fix for this.

**Comment by MikaelEdebro** [comment]
@SxDx fix is available in version 1.7.2
