### ISSUE TITLE
Feature Suggestion: Catches Click Outside Event

### ISSUE THREAD

**Issue by ThomasRalee** [MikaelEdebro/vue-airbnb-style-datepicker#100]
Can we have an event that overrides closes i.e. click outside or losing focus. It can be helpful, for instance:

If i want to trigger reset on the picker if user did not click apply, so the dates can be cleared if it's two way binded via Vuex and Computed Getter/Setter or Props.

**Comment by sikandartariq1** [comment]
I believe there we already have this event. 
@closed | Event emitted when datepicker is closed.

**Comment by MikaelEdebro** [comment]
Yes, the closed event should hopefully do the trick.
