### ISSUE TITLE
Import without Vue object

### ISSUE THREAD

**Issue by chancock09** [MikaelEdebro/vue-airbnb-style-datepicker#13]
Is it possible to use the datepicker component without registering with the vue global?

I'm trying to build some library code where consumers won't have access to my `Vue` object.

```
<template>
  <airbnb-style-datepicker :options="{}"/>
</template>

<script>
import { AirbnbStyleDatepicker } from 'vue-airbnb-style-datepicker'

export default = {
  components: {
    AirbnbStyleDatepicker
  }
}
</script>
```

Maybe options could be passed directly to the component instead of being passed at registration?

**Comment by danimalweb** [comment]
Is this possible?
