### ISSUE TITLE
dates not centered over month headings - asd__inner-wrapper 

### ISSUE THREAD

**Issue by blusol850** [MikaelEdebro/vue-airbnb-style-datepicker#14]
the style being applied to this wrapper to set the `margin-left` is causing  the following issues:

<img width="317" alt="screen shot 2018-05-09 at 10 13 15 pm" src="https://user-images.githubusercontent.com/35044908/39848754-cee03674-53d6-11e8-9362-271324a85895.png">

In the code inspector i can remove the inline style that's being computed and it displays fine. 
It is still inside the wrapper div as it should be.
The margin-left value the negative value of the width... ex: -360px.  I'm curious if that's how the JavaScript is supposed to compute it, or if there's a css conflict.

**Comment by MikaelEdebro** [comment]
It sounds like there is some CSS conflict causing this.

**Comment by salgua** [comment]
I have same problem using the component in AdminLTE. I think it depends by this https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/blob/d744730b146d4838a3fe032151310400fc509132/src/components/AirbnbStyleDatepicker.vue#L218

I solved adding this css fix on my component:

    <style>
        .asd__inner-wrapper {
            margin-left: 0 !important;
        }
    </style>
