### ISSUE TITLE
How to reset the state of the datepicker?

### ISSUE THREAD

**Issue by kindles** [MikaelEdebro/vue-airbnb-style-datepicker#17]
I need to reset/restart the state of the datepicker. it's possible ?

**Comment by MikaelEdebro** [comment]
Just reset the dates/models that you pass in as props to the datepicker (`:date-one & :date-two`).

And if you need to hide the datepicker, you can just trigger a click somewhere outside of the datepicker, for example on body.

```javascript
this.dateOne = ''
this.dateTwo = ''
document.querySelector('body').dispatchEvent(new Event('click'))
```

**Comment by kindles** [comment]
Thank you, I can reset the dates. It's possible to override the component to add a new button "reset"?

**Comment by MikaelEdebro** [comment]
I'm trying to keep the look and feel as close as possible to the original Airbnb datepicker, so I don't think I will add a Reset button. 
However, I assume you could always do some kind of hack, where you (with javascript) append a "Reset" button to the datepicker. A bit hacky, but it will probably work if that button is important for you.

**Comment by kindles** [comment]
thank you for your help !
