### ISSUE TITLE
ESLint cannot resolve import of the component

### ISSUE THREAD

**Issue by bigsee** [MikaelEdebro/vue-airbnb-style-datepicker#18]
Hey there!

Thanks for this awesome component!

I have been able to use it but found what is a possible ESLint issue. I followed the import instructions to import in main.js. Webpack is able to resolve the datepicker (which is functional), but ESLint keeps throwing me errors:

![screen shot 2018-05-22 at 18 35 13](https://user-images.githubusercontent.com/11768967/40376836-a9b44d72-5def-11e8-9150-44523c3f16d5.png)

No errors are thrown for other modules I've imported, so I don't _think_ the issue is at the ESLint end. 

![screen shot 2018-05-22 at 18 41 21](https://user-images.githubusercontent.com/11768967/40376886-ccaa0966-5def-11e8-98d3-849103c941cd.png)

...and I would rather not disable this rule if I can avoid it. I'm using the [AirBnb base](https://www.npmjs.com/package/eslint-config-airbnb) if that helps. 

Any ideas how we might resolve?

Thanks again!

**Comment by MikaelEdebro** [comment]
Strange! I just tried installing a fresh `vue init webpack test-datepicker`, with the AirBnb preset, and it's working fine.
Can you test removing node_modules and run `npm install` again?

**Comment by MikaelEdebro** [comment]
@bigsee Are you still having issues? If not, id like to close this issue.
