### ISSUE TITLE
Not trigger in modal

### ISSUE THREAD

**Issue by de-don** [MikaelEdebro/vue-airbnb-style-datepicker#20]
I have two datepicker, one in the modal window, and one outside it. Trigger-element-id are different.
When I show modal, datepicker not trigger on my input :(

I use bootstrap-vue, and component bModal

**Comment by Phantom75** [comment]
I'm having a similar issue. I have a datepicker in a component. When I call the component directly, all works fine. When I nest the component in another component though, the picker window does not appear.

**Comment by MikaelEdebro** [comment]
Could you create a Codepen or something where you recreate this?

**Comment by Phantom75** [comment]
I've not worked with codepen yet, sorry, and I am moving these days - sorry for being sloppy:
Basically:
Detail.vue
<template>
  <Datepicker></Datepicker>
</template>

<script>
import Datepicker from '....'
</script>

Master.vue
<template>
  <Detail></Detail>
</template>
<script>
import Detail from '....'>
component: {Detail}
<script>

If you call Detail directly, all is super fine and neat. If you call Master with Detail as a child component, the calendar does not appear.

Let me know if that helps, if not, I'll create a working example later.

**Comment by danwenzel** [comment]
Hi @MikaelEdebro .  I am having the same issue.  The datepicker does not open inside of a vue-bootstrap modal.

Here is a codepen that demonstrates the issue: https://codepen.io/danwenzel/pen/mQEKGP

**Comment by danwenzel** [comment]
@MikaelEdebro - Any help on this?

**Comment by MikaelEdebro** [comment]
Please update to latest version. I did some fixes that should hopefully solve this.

**Comment by MikaelEdebro** [comment]
I tried updating you codepen to v 2.4.0 and it seems to be working. 🙂

**Comment by danwenzel** [comment]
Works perfectly.  Thank you!

**Comment by VIRGO96** [comment]
> 2.4.0

It has started to appear again in 2.7.1 v if you could look in to it

**Comment by VIRGO96** [comment]
> Works perfectly. Thank you!

its not working in vuetify dialogs
