### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by wijnho** [MikaelEdebro/vue-airbnb-style-datepicker#21]
Having this error while use with Nuxt.js

The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by MikaelEdebro** [comment]
I gladly accept a PR for this. I have never used Nuxt.js, and unfortunately I don't have time right now to learn it. :/

**Comment by MikaelEdebro** [comment]
@nicholasnet Thanks for your input! Sounds logical that window isn't available on the server. However if it's due to that, this must be a very common issue for other plugins as well?!

Unfortunately I don't have time to tackle this issue at the moment, but hopefully someone else with experience in Nuxt.js could look in to this. :)

**Comment by mirobossert** [comment]
@nicholasnet i guess if you add the ssr option to the plugin in your nuxt.config.js it should be working as expected:

```
plugins: [
  { src: '~/plugins/vue-airbnb-style-datepicker.js', ssr: false }
]
```
https://nuxtjs.org/api/configuration-plugins/

**Comment by coleww** [comment]
in addition to the lines in `data()` that @nicholasnet pointed out, it also looks like there is some `window` related stuff happening in `created()`, which wouldn't work on the server either. https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/blob/master/src/components/AirbnbStyleDatepicker.vue#L324-L336

if those lines were moved into `mounted()` then this should work in SSR. I can make a PR for this in a few weeks once I have a codebase set up to actually test the SSR in 😆
