### ISSUE TITLE
Styles are set with JS

### ISSUE THREAD

**Issue by kleusch** [MikaelEdebro/vue-airbnb-style-datepicker#24]
Hi,

is there a special reason why you are setting the colors with JS in style tag instead of using CSS classes?
I need to style everything with CSS and it would not be nice to use !important for that.

It would be great if you could remove this or give an option to handle this (e.g. set the color object to empty).

**Comment by MikaelEdebro** [comment]
The reasons is because I want to allow setting colors when bootstrapping the datepicker:
https://mikaeledebro.gitbooks.io/vue-airbnb-style-datepicker/INSTALLATION.html#plugin-options
