### ISSUE TITLE
Set CSS class for date-one and date-two

### ISSUE THREAD

**Issue by kleusch** [MikaelEdebro/vue-airbnb-style-datepicker#25]
Could you give us a CSS classes based on the current state?

E.g.
Nothing selected - no class
First date selected - class "date-one-selected"
Second date selected - class "date-two-selected"

I need this for hover state. When nothing (or all) is selected, the hover state should be another than when only the first date is selected.

For the hover effects we could set in wrapper class:
` wrapperClasses() {
      return {
        'asd__wrapper--datepicker-open': this.showDatepicker,
        'asd__wrapper--full-screen': this.showFullscreen,
        'asd__wrapper--inline': this.inline,
        'asd__wrapper--selected-date-one': this.selectedDate1,
        'asd__wrapper--selected-date-two': this.selectedDate2,
      }`
Then I could set the hover styles on --selected class according to wrapper --selected-date-one or two.

And for default view without hover directly in day
` :class="{
                      'asd__day--enabled': dayNumber !== 0,
                      'asd__day--empty': dayNumber === 0,
                      'asd__day--disabled': isDisabled(fullDate),
                      'asd__day--selected': selectedDate1 === fullDate || selectedDate2 === fullDate,
                      'asd__day--selected-date-one': selectedDate1,
                      'asd__day--selected-date-two': selectedDate2,
                      'asd__day--in-range': isInRange(fullDate)
}"`
Then I could give the selected first and second date individual looks.

**Comment by MikaelEdebro** [comment]
Sounds like a good idea! If you have time, please submit a PR. Otherwise I can probably have a look at it in the near future.

**Comment by MikaelEdebro** [comment]
#
