### ISSUE TITLE
CSS component style force lowercase for Day and Month name

### ISSUE THREAD

**Issue by matinfo** [MikaelEdebro/vue-airbnb-style-datepicker#26]
Easy one:

```
.asd__month-name,
.asd__day-title {
    text-transform: capitalize !important;
}
```

**Comment by mikob** [comment]
Yes, I noticed the month days and weekday names are lowercased in this component, but capitalized on Airbnb. @MikaelEdebro would you accept a PR that makes the casing consistent with Airbnb?
