### ISSUE TITLE
Getting all dates in range (accounting for disabled dates)

### ISSUE THREAD

**Issue by Reached** [MikaelEdebro/vue-airbnb-style-datepicker#3]
Hi Mikael,

Great work on this component, was looking for something like this for a project im doing! How would I retrieve the dates in my range accounting for disabled dates? I guess some custom logic would be needed to achieve this currently? :)

Bonus question: is it intentional that you can currently select dates where some dates inbetween are disabled/unavailable?

Keep up the great work :)

**Comment by MikaelEdebro** [comment]
Yes you need to handle this on your side. I guess you can just handle it when the `@date-two-selected` (and/or *@date-one-selected`) event is fired. Like use date-fns or something to count the days between dateOne and dateTwo.

About the disabled dates. They only block selecting the exact disabled date, but there is no logic that you cannot select a range with a disabled date.
