### ISSUE TITLE
Clear dates

### ISSUE THREAD

**Issue by VincentMRA** [MikaelEdebro/vue-airbnb-style-datepicker#31]
Hi,

how can i clear the dates? tried to add a function on the click cancel button but no event is emitted on the click button.
any recommedation on how to implement this clear dates functionality?

**Comment by MikaelEdebro** [comment]
Just added a `@cancelled` event when user clicks cancel. So maybe you can use this. Available in v 1.9.2

**Comment by osnielcainzos** [comment]
HI, 

Im trying to use the component inside a vuetify dialog (modal window), but once the calendar is open it wont close anymore clicking on the trigger or on the modal area..

any advice ?

thanks

**Comment by MikaelEdebro** [comment]
@osnielcainzos Seems there are some issues with this plugin together with modals in Vuetify. I'm going to try to solve these issues.

**Comment by osnielcainzos** [comment]
thanks @MikaelEdebro 

is there a way to close the calendar when second date is selected ? Im trying setting the trigger to false in the event but nothing happens.
