### ISSUE TITLE
Making API min/end date more consistent

### ISSUE THREAD

**Issue by mikob** [MikaelEdebro/vue-airbnb-style-datepicker#32]
Would you accept a PR changing `end-date` to `max-date`, everywhere? Because currently it's  inconsistent, it should either be `min-date` and `max-date` or `start-date` and `end-date`. I prefer min and max.

**Comment by MikaelEdebro** [comment]
I hear you, but I don't think it justifies a breaking change for this little thing. Of course, you could keep support for both for a time, but that would only complicate the code.
