### ISSUE TITLE
When min-date is set to a future date, the calendar should default to the month of that min-date

### ISSUE THREAD

**Issue by daamsie** [MikaelEdebro/vue-airbnb-style-datepicker#38]
Firstly, thanks for creating this. It's working like a charm for me mostly. 

Came across this unexpected behaviour where the default shown month in the calendar is non-ideal.

To reproduce:

1. Set a min-date that is dynamic
2. Update this min-date to a future month (ie, from a related datepicker)
3. Trigger the calendar. 

It will show the initial min-date's calendar month which consists of non-selectable dates. 

Expected behaviour: go to the month where the min-date falls by default. 

Bonus: add an option to set the default month to show when calendar is triggered. I believe this property is called "initialVisibleMonth" in the Airbnb version.

**Comment by daamsie** [comment]
After some more investigation, I discovered this is only an issue when the min-date is dynamic and is updated.

In my particular use-case, I have two datepickers and I want the second datepicker to update the min-date based on the date in the first datepicker.

**Comment by daamsie** [comment]
I have created a fix for this issue. If you would like to use it, let me know and I'll create a PR. 
https://github.com/daamsie/vue-airbnb-style-datepicker/commit/46733af6a296cbe603b3ab269d746a2cf522d112

**Comment by MikaelEdebro** [comment]
@daamsie Yes please create a PR. Sounds like a good addition!

**Comment by daamsie** [comment]
Done

**Comment by MikaelEdebro** [comment]
Available in latest version. Thanks for your contribution! 🙂
