### ISSUE TITLE
Can´t load component

### ISSUE THREAD

**Issue by Pulstarter** [MikaelEdebro/vue-airbnb-style-datepicker#39]
Hi!

I am receiving the following error:

**[Vue warn]: Unknown custom element: <airbnbstyledatepicker> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)**

I am using Laravel 5.4 and Vue 2 with webpack.

I have the following on app.js:

```
import AirbnbStyleDatepicker from 'vue-airbnb-style-datepicker'
require('vue-airbnb-style-datepicker/dist/styles.css');
Vue.use(AirbnbStyleDatepicker);
```

npm run dev builds fine, but it can´t find the component. Any ideas?

Best regards

**Comment by Pulstarter** [comment]
Hi!

I remove node_modules with no lukc. After several tests, it works by changing AirbnbStyleDatepicker for airbnb-style-datepicker in HTML.

Thanks!

**Comment by somecallmejosh** [comment]
I'm having a similar issue.
````
./node_modules/vue-airbnb-style-datepicker/dist/vue-airbnb-style-datepicker.es.js
Module not found: Error: Can't resolve 'date-fns/add_days' in '/Users/joshuabriley/go/vue-components/node_modules/vue-airbnb-style-datepicker/dist'
 @ ./node_modules/vue-airbnb-style-datepicker/dist/vue-airbnb-style-datepicker.es.js 12:0-40
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/main.js
````
