### ISSUE TITLE
Year/Month selection

### ISSUE THREAD

**Issue by matthieudou** [MikaelEdebro/vue-airbnb-style-datepicker#40]
Hello, 

First, thank you. This datepicker is one of the best that I found 😄 

I was wondering if it was possible to implement a kind of Month selection and year selection when clicking on the year.

Thanks by advance for your answer

Matthieu

**Comment by MikaelEdebro** [comment]
Thanks, glad you like it!

Sounds like a good idea! I'll add it to the TODO list.

**Comment by aphilippartd** [comment]
+1 !! Would love to know once it's out!!

**Comment by ilyaztsv** [comment]
+1 It would be great!

**Comment by coleww** [comment]
this is a desired feature at my job, and i should have time to work on it this month.

I was thinking of handling this by adding a flag for `showMonthYearSelect` which if  true, would render a select input for the month and year text that is styled to remove the default select border/background and look like clickable text. That way the dropdown automatically gets the accessibility/mobile benefits of using a native select input. 
If users wanted to use a custom select there could also be a slot added for doing that.

**Comment by daamsie** [comment]
I like your version @coleww . How would we decide how many years there are available to choose from?

**Comment by MikaelEdebro** [comment]
@coleww I like it. Looks simple to use, and not to obtrusive. :)

Maybe have the ability to specify year span in config?

**Comment by coleww** [comment]
@daamsie  @MikaelEdebro  I was thinking it would either use the minDate/maxDate, or you could pass a year range as a prop somehow, or it would fallback to a default of +/- 10 years from the current date

For the slot, that was just an idea because HTML select inputs are difficult to style with CSS. I would personally never use it, and can just not implement it :D

**Comment by MikaelEdebro** [comment]
Released in 2.2.0
