### ISSUE TITLE
Highlighting today's date

### ISSUE THREAD

**Issue by voke** [MikaelEdebro/vue-airbnb-style-datepicker#44]
Wouldn't it be nice to have an option to highlight current date? E.g. using a color or underline. 
<img width="291" alt="highlight" src="https://user-images.githubusercontent.com/53462/43762979-c46f3944-9a29-11e8-82f5-776190ddaa4d.png">

**Comment by MikaelEdebro** [comment]
#47 
Added class `.asd__day--today`. I think that will suffice. That way you can style however you want.
