### ISSUE TITLE
Can i set active current date?

### ISSUE THREAD

**Issue by febyolaaldo** [MikaelEdebro/vue-airbnb-style-datepicker#48]
i want to set active current date, what can i do?

**Comment by febyolaaldo** [comment]
yes i know if i set in the props dateOne will make active date, but i want to set today highlighted in range mode (not in single mode) without set props, just highlighted today. Is it possible ?

**Comment by MikaelEdebro** [comment]
Yes, but you have to add your own styles.
In the most recent version, I added a CSS class on todays date:
`.asd__day--today`

You probably need to use `!important` to override the styles set by inline styles (like background color etc).

**Comment by febyolaaldo** [comment]
oh i see, thanks @MikaelEdebro

**Comment by ChristophAnastasiades** [comment]
It would be awesome if you could do the same with the current month. So something like `asd__month--today`, that way I could make sure to hide the "previous month" button so that no past months can be displayed.
