### ISSUE TITLE
Package conflicting with vuetify, causing an error

### ISSUE THREAD

**Issue by MrToxy** [MikaelEdebro/vue-airbnb-style-datepicker#51]
"vue-airbnb-style-datepicker": "^1.9.0"
 "vuetify": "^1.2.5"

The error is not that easy to understand since it happens everywhere even if it doesn't even have a vue-airbnb-style-datepicker, so I t hink this is a global listener which should not be the case.

But the error I get is the following:
```
Uncaught TypeError: vnode.context[binding.expression] is not a function
    at HTMLBodyElement.el.event (vue-airbnb-style-datepicker.es.js:697)
```
The stack trace:
`el.event @ vue-airbnb-style-datepicker.es.js:697`

This causes the vuetify component not to be able to close when clicking outside it's span area.
The affected component works properly once vue-airbnb-style-datepicker plugin is disabled so it is a problem with this event handling.

Edit:
I've tracked the issue down, and its due to de click outside directive which is being handled globally instead of being contained in the component scope, this is affecting all other elements like comboboxes, dropdown menus, preventing them from closing in

**Comment by febyolaaldo** [comment]
for combobox just add props `:menu-props="{closeOnClick: true}"` i think

**Comment by nazarblade** [comment]
@MrToxy , could you please share the solution, cause i tried with `:menu-props="{closeOnClick: true}"` and it did not help.

**Comment by MrToxy** [comment]
@nazarblade there's no simple solution, however with the new vuetify updates this issue was solved (aparently) but nontheless the problem lies within this click-outside directive injected by this plugin and Im sure this will affect other frameworks that have the same mechanics.
The only "scalable" thing I can think of to solve this is by forking the project, comment the use of the directive and point the package in package.json to your new package.
The owner really needs to take a look at this tho

**Comment by febyolaaldo** [comment]
@nazarblade like this, but it will show error like @MrToxy said. Instead the component can hide.

![image](https://user-images.githubusercontent.com/14918616/48597905-d0a87c80-e992-11e8-8e57-7a67878855f3.png)

but still have error on console 

![image](https://user-images.githubusercontent.com/14918616/48598090-c044d180-e993-11e8-9327-d78cb397a2b5.png)

**Comment by MrToxy** [comment]
The error persists, still affecting other components. It boggles me why the hell the click outside directive directive was instantiated globally in the first place... doesn't make sense. should be container to the package itself

**Comment by MikaelEdebro** [comment]
Hi guys! Could you please update to v2.3.0 and test if this have been resolved. I did some fixes, and at least with the modal it seems to be working fine now. So hopefully other issues have been resolved as well.

**Comment by MrToxy** [comment]
@MikaelEdebro thank you for the update, as far as I can see this update fixed the issue (thank you very much, this was a pressing issue with the client). Ill test it along this day but for this particular issue I will be closing it for at the end of the day.

**Comment by TolrenFrank** [comment]
It is because duplicated of library I think.

import clickOutside from "../directives/click-ouside.js";

You can find import part above.
Plz remove one thing.
Hope your works going well!!!
