### ISSUE TITLE
Use multiple Datepickers (same date range) on the same page?

### ISSUE THREAD

**Issue by jackbarham** [MikaelEdebro/vue-airbnb-style-datepicker#66]
I'm working on a page where the Datepicker is in its own custom component, but the same component is added twice (it's a long page).

When I click to open the first Datepicker, it's jumping to the second one.

Does anyone have suggestions or implemented two on a single page?

I know this is not a bug, but I've tried other places.

**Comment by MikaelEdebro** [comment]
You have to make sure the trigger id is unique. Pass it on as a prop.

**Comment by jackbarham** [comment]
Of course, that works. Thank you.

**Comment by Vishanth** [comment]
is there a value to capture the trigger-element-id and the value both in the date-one-selected function?

I'm trying to use the AirbnbStyleDatepicker inside a **v-for** and dynamically setting the trigger-element-id (it's unique). But when the date is selected, I want to capture the value and the trigger-element-id both in the method invoked from date-one-selected. 

Any lead?
