### ISSUE TITLE
'Element not defined' error while exporting/importing from the plugin file

### ISSUE THREAD

**Issue by MrToxy** [MikaelEdebro/vue-airbnb-style-datepicker#68]
I have a plugin file that initializes the the plugin, like so:

```
import Vue from 'vue'
import AirbnbStyleDatepicker from 'vue-airbnb-style-datepicker'
// import component and stylesheet
import 'vue-airbnb-style-datepicker/dist/vue-airbnb-style-datepicker.min.css'

// see docs for available options
const options = {
}
Vue.use(AirbnbStyleDatepicker, options)
```

Since the plugin doesn't have i18n support from the start I was trying to do a little trick to update the monthNames option and this is when I came to find an error.

So when trying to export a function from the plugin like:

```
export function update(){
    
}
```
And on another file importing it it throws an error triggered from ''node_modules/vue-airbnb-style-datepicker/dist/vue-airbnb-style-datepicker.cjs.js'

The error dump is:

```
var isBefore = _interopDefault(require('date-fns/is_before'));
var isAfter = _interopDefault(require('date-fns/is_after'));
var isValid = _interopDefault(require('date-fns/is_valid'));

/* eslint-disable */
if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.matchesSelector || Element.prototype.mozMatchesSelector || Element.prototype.msMatchesSelector || Element.prototype.oMatchesSelector || Element.prototype.webkitMatchesSelector || function (s) {
    var matches = (this.document || this.ownerDocument).querySelectorAll(s);
    var i = matches.length;

    while (--i >= 0 && matches.item(i) !== this) {}
```
Lines 22-33

**Comment by MikaelEdebro** [comment]
Is it not sufficient to just pass your localized monthNames, like:
```js
import Vue from 'vue'
import AirbnbStyleDatepicker from 'vue-airbnb-style-datepicker'
// import component and stylesheet
import 'vue-airbnb-style-datepicker/dist/vue-airbnb-style-datepicker.min.css'

// see docs for available options
const options = {
   monthNames: ['Januuuuuriai', 'Febrksks' 'etc']
}
Vue.use(AirbnbStyleDatepicker, options)
```

**Comment by MrToxy** [comment]
I've read the docs and I know where the month names should be, but Thats not my problem.
The problem right now is that Im using i18n to manage translations, the user can choose between 4 languages, Therefore the monthNames will differe from each other.
So i was exporting a function for the datepicker plugin and on i18n whenever the language gets changed I would pass into the datepicker plugin the new monthNames via that function.
It all sounds good on paper until you see that you cannot import the function (besides having it all correct) without getting an error from this package at the location I've described.
Not being able to import something from the module renders it pretty much usesull if you want to tailor its usage.

**Comment by MikaelEdebro** [comment]
One solution would probably be to reinstantiate the plugin whenever the user changes language.
I havn't tested it, but it might be worth a shot. I know I've done similar things with other plugins with success.
