### ISSUE TITLE
Setting icon is not override

### ISSUE THREAD

**Issue by tucheng0552** [MikaelEdebro/vue-airbnb-style-datepicker#70]
`<div><img src="~/assets/image/icon/global_icon_swiper_arrow_left.png" alt="" slot="previous-month-icon"><AirbnbStyleDatepicker .../></div>`

>  The icon is just displayed, no coverage. How to set it up correctly?

> AND

>I need to show the price below the date, can you add a slot for displaying custom content?

> Thanks

**Comment by MikaelEdebro** [comment]
You're using the wrong syntax:

```js
<airbnb-style-datepicker
  :trigger-element-id="'datepicker-trigger'"
  :mode="'single'"
  :date-one="dateOne"
  @date-one-selected="val => { dateOne = val }"
>
  <template slot="next-month-icon">Price: 100$</template>
</airbnb-style-datepicker>
```
