### ISSUE TITLE
close-after-select not working

### ISSUE THREAD

**Issue by malaquf** [MikaelEdebro/vue-airbnb-style-datepicker#76]
I've tried setting :close-after-select="true"  but it has no effect. The date picker remains open after selecting start/end dates.

**Comment by MikaelEdebro** [comment]
Which version are you using?

**Comment by malaquf** [comment]
Your response time was incredible fast! I've just debugged it and saw the property was not present, and then I checked the change history and saw this is a very new property. I'm currently updating the package, but I already saw that all should work just fine in the new source. Thanks a lot!

**Comment by malaquf** [comment]
Indeed it works just fine. Thanks for the great component! Looking forward to contribute somehow too.

**Comment by MikaelEdebro** [comment]
Yeah, this was recently added. :)
Good that it got resolved.
