### ISSUE TITLE
:mode="'single'" not working 

### ISSUE THREAD

**Issue by bilgino** [MikaelEdebro/vue-airbnb-style-datepicker#78]
:mode="'single'" is not working properly, please check example in the app component:
https://codesandbox.io/s/5xv36rn6rx

**Comment by tehuel** [comment]
The linked example is working for me, I can select days 1 or 8 of december.

I don't know what do you mean with not working, but maybe you have a problem with defining both `enabled-dates` and `disabled-dates` on the same date picker.

**Comment by bilgino** [comment]
I dont want to show the datepicker in "range"-mode |left-datepicker|right-datepicker|... I activated the single mode but its not working. My goal ist just to show one datepicker not two! thanx...

**Comment by tehuel** [comment]
The `:mode="'single'"` mode defines that you only select one date, in contrast wit the `:mode="'range'"` mode where you can select a pair of dates.

To show a single calendar you can set `:months-to-show="1"`. The default value is 2, [according to docs](https://mikaeledebro.gitbooks.io/vue-airbnb-style-datepicker/INSTALLATION.html#props-and-events).

**Comment by bilgino** [comment]
AH! Ok! Thanx...
