### ISSUE TITLE
HandleClickOutside fires when already closed

### ISSUE THREAD

**Issue by TomoGlavas** [MikaelEdebro/vue-airbnb-style-datepicker#8]
Just a small issue I found so far, handleClickOutside event should check if it is visible before emitting an event.

I had a hook on @closed that began firing on every click on the app, making api requests like every time.

P.S. The plugin is nicely done, cheers!

**Comment by MikaelEdebro** [comment]
This is fixed in 1.7.1.
https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/releases/tag/v1.7.1
