### ISSUE TITLE
Incorrect Component View (shifted Position)

### ISSUE THREAD

**Issue by mzotter** [MikaelEdebro/vue-airbnb-style-datepicker#82]
Hi, 
When I open the datepicker, everything works as it should be.
But when I click previousMonth 2 times, component shows incorrectly. => it happens when the initial DateOne or the empty new Date (to set focusedDate) is on the last "asd_month", the hidden one. 

Step 1 - shown correctly:
![bildschirmfoto 2018-12-17 um 14 51 41](https://user-images.githubusercontent.com/45843652/50091761-8114d500-020c-11e9-94fb-1e339ba7b58c.png)

Step 2 - after first click on previousMonth:
![bildschirmfoto 2018-12-17 um 14 51 51](https://user-images.githubusercontent.com/45843652/50091717-680c2400-020c-11e9-850d-bca7e1ae4b57.png)

Step 3 - after second click on previousMonth:
(the whole asd_month with selected DateOne should be the last asd_month (hidden))
![bildschirmfoto 2018-12-17 um 14 51 32](https://user-images.githubusercontent.com/45843652/50091785-94c03b80-020c-11e9-89c4-b82bf9645d77.png)

After that I also get following Error in the Dev Tools console from Chrome:
![bildschirmfoto 2018-12-17 um 15 03 30](https://user-images.githubusercontent.com/45843652/50091946-0dbf9300-020d-11e9-8354-41e7c37641b4.png)

![bildschirmfoto 2018-12-17 um 15 05 02](https://user-images.githubusercontent.com/45843652/50091987-26c84400-020d-11e9-9c64-0307f42a72e6.png)

It can be reproduced on ur Demo site: first DatePicker
http://htmlpreview.github.io/?https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/blob/master/docs/examples.html

_Originally posted by @mzotter in https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/issues/65#issuecomment-447858033_

I look forward to hearing from you.

**Comment by MikaelEdebro** [comment]
I'm not able to reproduce this on my local environment. However, I've added a small fix that will hopefully resolve this.
Please update to latest version.
