### ISSUE TITLE
Allow changing the range color when hovering

### ISSUE THREAD

**Issue by ChristophAnastasiades** [MikaelEdebro/vue-airbnb-style-datepicker#84]
I think it would be great to be able to visually show which range a user is about to select (just like Airbnb does). So I forked this project and added some changes. You can now set a prop `enableHoverRange` and define colors for the hovered range (text color, border color, background color). Also you can define a color for the currently hovered day.

Please have a look at the code here: https://github.com/ChristophAnastasiades/vue-airbnb-style-datepicker

**Comment by MikaelEdebro** [comment]
There was another PR that I just merged. Available in 2.7.0.
