### ISSUE TITLE
Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by panay** [MikaelEdebro/vue-airbnb-style-datepicker#85]
This error breaks here: `setTimeout(function(){n[0].focus()},10)`
At the `setFocusedDate` function, I think.

This occurs when I try to leave a page with the picker.

**Comment by MikaelEdebro** [comment]
Please try updating to most recent version (at least 2.6.1). I've added a small fix that I think should resolve this issue.

**Comment by alisspers** [comment]
We seem to be getting this error on a semi-regular basis still. We use version 2.7.1 of the lib.

I'm having a hard time reproducing the error myself but it's reported to Sentry from time to time. It seems to only affect mobile browsers (see attached image).

Any suggestions?

<img width="782" alt="Screenshot 2020-04-09 at 09 37 48" src="https://user-images.githubusercontent.com/208699/78870066-d1d5c000-7a45-11ea-8125-a843069ef697.png">

<img width="1132" alt="Screenshot 2020-04-09 at 09 33 30" src="https://user-images.githubusercontent.com/208699/78870078-d5694700-7a45-11ea-8648-107b51359322.png">
