### ISSUE TITLE
Vue is not defined on Examples page 

### ISSUE THREAD

**Issue by daamsie** [MikaelEdebro/vue-airbnb-style-datepicker#89]
Currently none of the examples on [this examples page](http://htmlpreview.github.io/?https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/blob/master/docs/examples.html) work

The error in the console is 

Uncaught ReferenceError: Vue is not defined
    at <anonymous>:3:5
    at loadJS (htmlpreview.js:85)
    at htmlpreview.js:56

**Comment by MikaelEdebro** [comment]
Should be fixed now. Something has broken with https://htmlpreview.github.io/ it seems. Moved the examples page to https://mikaeledebro.gitbooks.io/vue-airbnb-style-datepicker/examples.html
