### ISSUE TITLE
Custom date group

### ISSUE THREAD

**Issue by sikandartariq1** [MikaelEdebro/vue-airbnb-style-datepicker#90]
Can we add custom dates groups and style those groups differently?
Currently we have **enabled-dates**, **disabled-dates** groups. What if we can add a new group let's say **booked-dates** and maybe just by adding a class **asd__day--booked** to those dates will do the trick as we can easily then add custom style for those classes.

**Comment by sikandartariq1** [comment]
#91 something like this

**Comment by MikaelEdebro** [comment]
Sounds like a good idea. Let's continue the discussion in the pr. 🙂👍

**Comment by Hussainbhatti1** [comment]
+1
